version: '3.4'

services:
  todddo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44396
      - Kestrel__Certificates__Default__Path=/root/.aspnet/https/cert-aspnetcore.pfx 
      - Kestrel__Certificates__Default__Password=test
    ports:
      - "35573:80"
      - "44396:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro